#baseUrl = http://localhost:8080
@baseUrl = http://localhost:5263

### Create event
POST {{baseUrl}}/events
Content-Type: application/json

{
    "name": "Saturday Night Local",
    "participantUuid": "4a7b3c2d-1e2f-3a4b-5c6d-7e8f9a0b1c2d"
}

### Get event
GET {{baseUrl}}/events/f836fbaf-7b81-474e-9b53-478ad1ac2a15
